# KNN Classifier 

In [39]:
import numpy as np
import pandas as pd
from sklearn import neighbors,metrics
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import scale

In [148]:
wine_df = pd.read_csv('wine.data',header=None)

In [149]:
wine_df.columns = ['Class','Alcohol','Malic acid','Ash','Alcalinity of ash',
                'Magnesium','Total phenols','Flavanoids','Nonflavanoid phenols',
                'Proanthocyanins','Color intensity','Hue','OD280/OD315 of diluted wines','Proline']

In [150]:
wine_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
Class                           178 non-null int64
Alcohol                         178 non-null float64
Malic acid                      178 non-null float64
Ash                             178 non-null float64
Alcalinity of ash               178 non-null float64
Magnesium                       178 non-null int64
Total phenols                   178 non-null float64
Flavanoids                      178 non-null float64
Nonflavanoid phenols            178 non-null float64
Proanthocyanins                 178 non-null float64
Color intensity                 178 non-null float64
Hue                             178 non-null float64
OD280/OD315 of diluted wines    178 non-null float64
Proline                         178 non-null int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [56]:
X = wine_df.iloc[:,1:].values
target = np.squeeze(np.asarray(wine_df.iloc[:,0]))

print(X)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]


In [131]:
# The partition generator
kfold = KFold(n_splits=5,random_state=42,shuffle=True)

# The classifier model
knn = neighbors.KNeighborsClassifier(n_neighbors = 10)

# Cross validation
scores  = cross_val_score(estimator=knn,X = X, y=target, scoring='accuracy', cv=partition)

In [132]:
scores

array([0.72222222, 0.61111111, 0.63888889, 0.68571429, 0.74285714])

In [136]:
def k_cross_score(k,features,target):
    knn = neighbors.KNeighborsClassifier(n_neighbors = k)
    scores = cross_val_score(estimator=knn,X=features,y=target,scoring='accuracy',cv=kfold)
    return scores.mean()

In [137]:
k_scores = []
for k in range(1,51):
    score = k_cross_score(k,X,target)
    k_scores.append((k,round(score,2)))

In [145]:
k_scores.sort(key = lambda x:x[1], reverse=True)
#k_scores

In [139]:
with open('1.txt','w',encoding='utf-8') as fileout:
    print(k_scores[0][0], file=fileout, end='')
    
with open('2.txt','w',encoding='utf-8') as fileout:
    print(round(k_scores[0][1],2), file=fileout, end='')

In [140]:
stand_X = scale(X)

In [142]:
stand_k_scores = []
for k in range(2,51):
    score = k_cross_score(k,stand_X,target)
    stand_k_scores.append((k,round(score,2)))
    
stand_k_scores.sort(key = lambda x:x[1], reverse=True)

In [143]:
with open('3.txt','w',encoding='utf-8') as fileout:
    print(stand_k_scores[0][0], file=fileout, end='')
    
with open('4.txt','w',encoding='utf-8') as fileout:
    print(round(stand_k_scores[0][1],2), file=fileout, end='')

In [146]:
#stand_k_scores

In [147]:
stand_X 

array([[ 1.51861254, -0.5622498 ,  0.23205254, ...,  0.36217728,
         1.84791957,  1.01300893],
       [ 0.24628963, -0.49941338, -0.82799632, ...,  0.40605066,
         1.1134493 ,  0.96524152],
       [ 0.19687903,  0.02123125,  1.10933436, ...,  0.31830389,
         0.78858745,  1.39514818],
       ...,
       [ 0.33275817,  1.74474449, -0.38935541, ..., -1.61212515,
        -1.48544548,  0.28057537],
       [ 0.20923168,  0.22769377,  0.01273209, ..., -1.56825176,
        -1.40069891,  0.29649784],
       [ 1.39508604,  1.58316512,  1.36520822, ..., -1.52437837,
        -1.42894777, -0.59516041]])