In [1]:
import numpy as np
import pandas as pd

#skleaarn libraries
from sklearn import svm

In [2]:
svm_data = pd.read_csv('svm-data.csv',header=None)

In [3]:
svm_data

0     1     2
0  0.0  0.70  0.29
1  1.0  0.23  0.55
2  0.0  0.72  0.42
3  0.0  0.98  0.68
4  0.0  0.48  0.39
5  1.0  0.34  0.73
6  0.0  0.44  0.06
7  1.0  0.40  0.74
8  0.0  0.18  0.18
9  1.0  0.53  0.53

In [32]:
X = svm_data.iloc[:,[1,2]]
y = svm_data.iloc[:,0]

In [33]:
clf = svm.SVC(C=100000, random_state = 241, gamma='auto')

In [34]:
clf.fit(X,y)
clf

SVC(C=100000, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=241, shrinking=True, tol=0.001,
    verbose=False)

In [9]:
supportVectors = clf.support_

In [10]:
with open('svm.txt','w', encoding='utf-8') as fileout:
    print(*(supportVectors+1), file=fileout,sep=',',end='')

#  

# Text analysis with linear method svm

In [53]:
import numpy as np
import pandas as pd

#sklearn libraries
from sklearn import datasets, svm
from sklearn.model_selection import KFold, GridSearchCV
from sklearn.feature_extraction.text import TfidfVectorizer


In [11]:
newsgroups = datasets.fetch_20newsgroups(
                    subset='all', 
                    categories=['alt.atheism', 'sci.space']
             )

In [16]:
len(newsgroups.target)

1786

In [22]:
# How to count values in numpy array
unique, counts = np.unique(newsgroups.target,return_counts=True)
np.asarray((unique,counts)).T

array([[  0, 799],
       [  1, 987]], dtype=int64)

# Реализация SVM-классификатора
Реализация SVM-классификатора находится в классе sklearn.svm.SVC. Веса каждого признака у обученного классификатора хранятся в поле coef_. Чтобы понять, какому слову соответствует i-й признак, ***можно воспользоваться методом get_feature_names() у TfidfVectorizer:***

# Tfitvectorizer

In [129]:
from sklearn.feature_extraction.text import TfidfVectorizer
>>> corpus = [
...     'This is the first document.',
...     'This document is the second document.',
...     'And this is the third one.',
...     'Is this the first document?',
... ]
>>> vectorizer = TfidfVectorizer()
>>> xx = vectorizer.fit_transform(corpus)
>>> print(vectorizer.get_feature_names())
>>> print(xx.shape)

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
(4, 9)


#  How does the grid work?

In [40]:
grid = {'C': np.power(10.0, np.arange(-5, 6))} # the grid of the values we want to evaluate

cv = KFold(n_splits=5, shuffle=True, random_state=241) # For cross validation 
clf = svm.SVC(kernel='linear', random_state=241)   # Here is our estimator, the model to be tested
gs = GridSearchCV(clf, grid, scoring='accuracy', cv=cv) # This command will evaluate all given parameters
gs.fit(X, y) # We train the evaluator

GridSearchCV(cv=KFold(n_splits=5, random_state=241, shuffle=True),
             error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='linear',
                           max_iter=-1, probability=False, random_state=241,
                           shrinking=True, tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': array([1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02,
       1.e+03, 1.e+04, 1.e+05])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [42]:
gs.cv_results_

{'mean_fit_time': array([0.02663989, 0.00719237, 0.00699301, 0.00700459, 0.00658784,
        0.00820484, 0.0120008 , 0.0070065 , 0.0066    , 0.0071897 ,
        0.00699568]),
 'std_fit_time': array([4.02918591e-02, 3.92860460e-04, 9.93310287e-06, 1.52144682e-05,
        4.88392428e-04, 1.71720159e-03, 3.74081288e-03, 6.32092783e-04,
        4.98565769e-04, 3.96216772e-04, 6.26069811e-04]),
 'mean_score_time': array([0.03690386, 0.00340757, 0.00420575, 0.00339174, 0.00360842,
        0.00460052, 0.00599852, 0.0033977 , 0.00359612, 0.00401206,
        0.00379987]),
 'std_score_time': array([0.06629885, 0.00049036, 0.00040286, 0.00049704, 0.00047962,
        0.00079984, 0.00154754, 0.00049274, 0.00049462, 0.00063348,
        0.00038962]),
 'param_C': masked_array(data=[1e-05, 0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0,
                    1000.0, 10000.0, 100000.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False],
      

In [45]:
gs.best_estimator_

SVC(C=10.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=241,
    shrinking=True, tol=0.001, verbose=False)

In [46]:
gs.best_score_

0.8

In [47]:
gs.best_params_

{'C': 10.0}

In [49]:
gs.refit_time_

0.003999233245849609

#  Let's resolve the exercise of newsgrpoups

In [168]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(newsgroups.data)
#print(vectorizer.get_feature_names())

In [69]:
X[X.nonzero()]

matrix([[0.09177291, 0.09732963, 0.02575007, ..., 0.01134319, 0.30431308,
         0.01134319]])

In [71]:
y = newsgroups.target

In [74]:
#Evaluating the paramaters
grid = {'C':np.power(10.0,np.arange(-5,6))}
cv = KFold(n_splits=5,shuffle=True,random_state=241)
clf = svm.SVC(kernel='linear', random_state = 241)

gs = GridSearchCV(estimator=clf,param_grid=grid,scoring='accuracy',cv=cv)
gs.fit(X,y)

GridSearchCV(cv=KFold(n_splits=5, random_state=241, shuffle=True),
             error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='linear',
                           max_iter=-1, probability=False, random_state=241,
                           shrinking=True, tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': array([1.e-05, 1.e-04, 1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02,
       1.e+03, 1.e+04, 1.e+05])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='accuracy', verbose=0)

In [75]:
gs.cv_results_

{'mean_fit_time': array([ 8.33532481,  8.14600077,  9.60643797, 11.56671085,  7.33987556,
         4.35433178,  4.39620109,  4.2550025 ,  4.24779906,  4.61340408,
         4.23801231]),
 'std_fit_time': array([0.60193053, 0.22453513, 1.39103293, 1.62915704, 0.07858993,
        0.07469864, 0.0553501 , 0.17626649, 0.17307293, 0.19803916,
        0.12363596]),
 'mean_score_time': array([1.88678374, 1.93719149, 2.21226697, 3.1984169 , 1.72237134,
        1.00870681, 0.99299941, 0.95779805, 0.97400708, 0.98859577,
        0.98899574]),
 'std_score_time': array([0.14867695, 0.22746551, 0.52461983, 1.29632191, 0.13985277,
        0.13015322, 0.03499825, 0.06309952, 0.03950387, 0.05113287,
        0.08269522]),
 'param_C': masked_array(data=[1e-05, 0.0001, 0.001, 0.01, 0.1, 1.0, 10.0, 100.0,
                    1000.0, 10000.0, 100000.0],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False],
        fill_value='?',
             dt

In [78]:
# The best parameters
gs.best_estimator_
gs.best_params_
gs.best_score_
gs.refit_time_

{'C': 1.0}

In [196]:
# The classifier with the best parameters
best_clf = svm.SVC(kernel='linear',C=1.0,random_state=241)

In [197]:
# Train
best_clf.fit(X,y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=241,
    shrinking=True, tol=0.001, verbose=False)

In [206]:
# How to extract data and its indices
my_coef = np.abs(best_clf.coef_.data)
my_indices = best_clf.coef_.indices

needed_indices = my_indices[np.argsort(my_coef)][-10:]
print(needed_indices)

[22936 15606  5776 21850 23673 17802  5093  5088 12871 24019]


In [207]:
common_word = []
for i in needed_indices:
        common_word.append(vectorizer.get_feature_names()[i])

In [209]:
with open('svm text mining.txt','w',encoding='utf-8') as fileout:
    print(*sorted(common_word), file=fileout, end='')

In [139]:
# Or we can do it this way!

# Here we take the absolute number of every coef
weights_pos = np.abs(best_clf.coef_[0])
print(weights_pos.indices[:20])

#Then we get the indices of the sorted data
# And from them we take all that we need
weights_pos_sorted = np.argsort(weights_pos) #????????????? Does not work properly, I dont't why
common_words_indices = weights_pos_sorted[-10:]
common_words = np.asarray(vectorizer.get_feature_names())[common_words_indices]

[ 0  1  5  7  8  9 23 31 32 34 35 36 37 41 47 49 50 51 53 55]
