In [24]:
import numpy as np
import pandas as pd
from scipy import stats
#from matplotlib import pyplot as plt

In [2]:
randMatrix = np.random.normal(loc = 3, scale = 5, size = (1000,50))
print(randMatrix)

[[ 5.59921881  3.58376172  8.01681694 ... -0.44765513  6.41528849
   6.57649259]
 [ 2.32151439 -3.05898607  0.94406846 ... -4.15427013 -0.59575667
   1.26363095]
 [ 2.85043727  5.85173304  1.64962047 ...  0.48288666  3.89743962
   9.69391212]
 ...
 [ 9.39529505  3.00997847 -9.77463982 ...  7.47703693  5.95935629
   7.14999995]
 [ 5.07243087 -1.31683962  2.2088775  ...  1.88867807  3.29485734
  -4.78972857]
 [ 0.46531988  4.8470098  12.56118345 ...  9.34903388  6.54975347
  16.13726043]]


In [9]:
colMean = np.mean(randMatrix, axis=0)
colSTD = np.std(randMatrix, axis=0)
normalMatrix = (randMatrix - colMean)/colSTD
print(colMean)

[2.80317152 3.19838876 2.98172217 2.6729711  3.06016519 3.0518145
 3.21767632 2.99186763 3.10647399 2.95102921 3.12065748 3.01113883
 3.12164102 2.86656841 3.349957   3.07495993 3.16540604 2.97057845
 3.00963724 3.09871512 3.18289927 2.77140204 2.92604142 2.91721223
 3.11271322 3.13427681 3.11575614 2.97434716 2.95159073 2.6202017
 2.79895333 2.60634569 2.99813393 3.07292409 2.85153641 3.16510396
 3.02694263 2.83355101 3.08894962 2.94941325 3.08837548 3.22051641
 2.93346467 2.9079135  2.70892424 3.23744949 3.10568107 2.81493917
 2.95706227 3.04465039]


In [12]:
x = np.array([[2,5],[3,7]])
y = np.array([-1,0])
print(x,y)
print(x*y)

[[2 5]
 [3 7]] [-1  0]
[[-2  0]
 [-3  0]]


In [13]:
Z = np.array([[4, 5, 0], 
             [1, 9, 3],              
             [5, 1, 1],
             [3, 3, 3], 
             [9, 9, 9], 
             [4, 7, 1]])

In [22]:
sum_row = np.sum(Z, axis=1)
np.nonzero(sum_row > 10)

(array([1, 4, 5], dtype=int64),)

In [27]:
A = np.eye(3)
B = np.eye(3)
print(A,end="\n\n")
print(B)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
VAB = np.vstack((A,B))
print(VAB)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [31]:
HAB = np.hstack((A,B))
print(HAB)

[[1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1.]]


## Titanic Disaster

In [6]:
test = pd.read_csv('test.csv',index_col='PassengerId', header = 0)

In [8]:
test.head()

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

              Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
PassengerId                                                       
892          34.5      0      0   330911   7.8292   NaN        Q  
893          47.0      1      0   363272   7.0000   NaN        S  
894          62.0      0      0   240276   9.6875   NaN        Q  
895          27.0      0      0   315154   8.6625   NaN        S  
896          22.0      1      1  3101298  12.2875   NaN        S

In [9]:
test[:10]

Pclass                                          Name     Sex  \
PassengerId                                                                 
892               3                              Kelly, Mr. James    male   
893               3              Wilkes, Mrs. James (Ellen Needs)  female   
894               2                     Myles, Mr. Thomas Francis    male   
895               3                              Wirz, Mr. Albert    male   
896               3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   
897               3                    Svensson, Mr. Johan Cervin    male   
898               3                          Connolly, Miss. Kate  female   
899               2                  Caldwell, Mr. Albert Francis    male   
900               3     Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female   
901               3                       Davies, Mr. John Samuel    male   

              Age  SibSp  Parch     Ticket     Fare Cabin Embarked  
PassengerId                                                         
892          34.5      0      0     330911   7.8292   NaN        Q  
893          47.0      1      0     363272   7.0000   NaN        S  
894          62.0      0      0     240276   9.6875   NaN        Q  
895          27.0      0      0     315154   8.6625   NaN        S  
896          22.0      1      1    3101298  12.2875   NaN        S  
897          14.0      0      0       7538   9.2250   NaN        S  
898          30.0      0      0     330972   7.6292   NaN        Q  
899          26.0      1      1     248738  29.0000   NaN        S  
900          18.0      0      0       2657   7.2292   NaN        C  
901          21.0      2      0  A/4 48871  24.1500   NaN        S

In [13]:
test["Sex"].value_counts()

male      266
female    152
Name: Sex, dtype: int64

In [2]:
data = pd.read_csv("titanic.csv",index_col='PassengerId', header = 0)

In [4]:
data.head()

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S

In [5]:
data[:10]

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C

In [6]:
total = len(data.index)

In [8]:
genre = data["Sex"].value_counts()
male = genre.male
female = genre.female

with open('1.txt','w', encoding = 'utf-8') as infile:
    print(male, female, file = infile, end='')

In [9]:
print(total, male, female)

891 577 314


In [10]:
## data.size ## 
data.shape

(891, 11)

In [14]:
survived = len(data[data["Survived"] == 1])
survived

with open('2.txt','w', encoding = 'utf-8') as infile:
    print(round(100*(survived/total),2), file = infile, end='')

In [17]:
_1st_Class = len(data[data["Pclass"] == 1])
_1st_Class

with open('3.txt','w', encoding = 'utf-8') as infile:
    print(round(100*(_1st_Class/total),2), file = infile, end='')

In [23]:
Age  = data["Age"]
##Age.dropna(inplace = True)
print(Age)

ageMean = np.nanmean(Age)
ageMedian = np.nanmedian(Age)

with open('4.txt','w', encoding = 'utf-8') as infile:
    print(round(ageMean, 2), ageMedian, file = infile, end='')

PassengerId
1      22.0
2      38.0
3      26.0
4      35.0
5      35.0
       ... 
887    27.0
888    19.0
889     NaN
890    26.0
891    32.0
Name: Age, Length: 891, dtype: float64


In [24]:
print(*stats.mode(Age)[0])

24.0


In [25]:
data[:10]

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C

In [26]:
pearsonR = data["SibSp"].corr(data["Parch"])

with open('5.txt','w', encoding = 'utf-8') as infile:
    print(round(pearsonR,2), file = infile, end='')

In [27]:
data["Parch"].corr(data["SibSp"])

0.4148376986201515

In [28]:
stats.pearsonr(data["SibSp"],data["Parch"])

(0.4148376986201556, 2.2418236681390328e-38)

In [36]:
femaleNames = data[data["Sex"] == 'female']["Name"]


femaleNames = list(femaleNames)

femaleNames = list(map(lambda x:x.split(","),femaleNames))

In [37]:
femaleNames = np.array(femaleNames)
femaleNames

array([['Cumings', ' Mrs. John Bradley (Florence Briggs Thayer)'],
       ['Heikkinen', ' Miss. Laina'],
       ['Futrelle', ' Mrs. Jacques Heath (Lily May Peel)'],
       ['Johnson', ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)'],
       ['Nasser', ' Mrs. Nicholas (Adele Achem)'],
       ['Sandstrom', ' Miss. Marguerite Rut'],
       ['Bonnell', ' Miss. Elizabeth'],
       ['Vestrom', ' Miss. Hulda Amanda Adolfina'],
       ['Hewlett', ' Mrs. (Mary D Kingcome) '],
       ['Vander Planke', ' Mrs. Julius (Emelia Maria Vandemoortele)'],
       ['Masselmani', ' Mrs. Fatima'],
       ['McGowan', ' Miss. Anna "Annie"'],
       ['Palsson', ' Miss. Torborg Danira'],
       ['Asplund', ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'],
       ["O'Dwyer", ' Miss. Ellen "Nellie"'],
       ['Spencer', ' Mrs. William Augustus (Marie Eugenie)'],
       ['Glynn', ' Miss. Mary Agatha'],
       ['Vander Planke', ' Miss. Augusta Maria'],
       ['Nicola-Yarred', ' Miss. Jamila'],
       ['Ahlin', ' Mr

In [57]:
fullname = []
for name in femaleNames:
    fullname.append(name[1].strip())
#fullname

firstname = []
for name in fullname:
    name = name.split()
    if name[0] == 'Miss.':
        for elt in name[1:]: 
            if elt[0] != '"' and elt[0] != '(':
                firstname.append(elt)
            if elt[0] == '(':
                break
    else :
        for elt in name[1:]: 
            if elt[0] == '(':
                nnew = ''.join(elt[1:].split(')'))
                firstname.append(nnew)
                break
#firstname
    

In [58]:
popularName = stats.mode(firstname)

with open('6.txt','w', encoding = 'utf-8') as infile:
    print(*popularName[0], file = infile, end='')

###  

##  

# Decision trees

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [6]:
data = pd.read_csv("titanic.csv",index_col='PassengerId', header = 0)

In [7]:
data[:10]

Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
6                   0       3   
7                   0       1   
8                   0       3   
9                   1       3   
10                  1       2   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
6                                             Moran, Mr. James    male   NaN   
7                                      McCarthy, Mr. Timothy J    male  54.0   
8                               Palsson, Master. Gosta Leonard    male   2.0   
9            Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
10                         Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             SibSp  Parch            Ticket     Fare Cabin Embarked  
PassengerId                                                          
1                1      0         A/5 21171   7.2500   NaN        S  
2                1      0          PC 17599  71.2833   C85        C  
3                0      0  STON/O2. 3101282   7.9250   NaN        S  
4                1      0            113803  53.1000  C123        S  
5                0      0            373450   8.0500   NaN        S  
6                0      0            330877   8.4583   NaN        Q  
7                0      0             17463  51.8625   E46        S  
8                3      1            349909  21.0750   NaN        S  
9                0      2            347742  11.1333   NaN        S  
10               1      0            237736  30.0708   NaN        C

In [69]:
#ATTRIBUTES
clean_data = data.dropna(subset = ['Age'])
X = clean_data[['Pclass','Fare','Age','Sex']].values

#lABEL
y = clean_data[['Survived']]
y = np.squeeze(np.asarray(y))

In [70]:
features = ['Pclass','Fare','Age','Sex']

In [71]:
#Sex conversion into binar objects
sex_mapping = {
    'male':0,
    'female':1
}
for i in range(len(X)):
    X[i,3] = sex_mapping[X[i,3]]

#Split the data into train and test 
#X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2)

In [79]:
# We create a model
clf = DecisionTreeClassifier(random_state=241)
#We train our model
clf.fit(X,y)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=241, splitter='best')

In [80]:
#predictions
      #predictions = clf.predict(X_test)
      #accuracy = accuracy_score(y_test,predictions)

In [81]:
#Features importance

importances = clf.feature_importances_

feat_importance = []
for i, value in enumerate(importances):
    feat_importance.append((i,value))
    
# We sort the features indexes from the most important to the least important     
feat_importance.sort(key = lambda x: x[1], reverse = True)
print(feat_importance)

[(3, 0.3005122109582393), (1, 0.2953846784065746), (2, 0.25658494964003575), (0, 0.14751816099515025)]


In [83]:
# We return the first two most important features

with open('answer.txt', 'w', encoding='utf-8') as fileout:
    print(
        features[feat_importance[0][0]],
        features[feat_importance[1][0]],
        file = fileout,
        end=''
    )